name: End-to-End Tests

on: pull_request

jobs:
  end-to-end-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.14'

    - name: Install Chakra
      run: |
        pip install .

    - name: Install PARAM
      run: |
        git clone https://github.com/facebookresearch/param.git
        cd param/et_replay
        git checkout 884a1f0154a16e2c170e456f8027f2646c9108ae
        sed -i '/param_bench/d' pyproject.toml
        pip install .

    - name: Install HTA
      run: |
        git clone https://github.com/facebookresearch/HolisticTraceAnalysis.git
        cd HolisticTraceAnalysis
        git checkout d731cc2e2249976c97129d409a83bd53d93051f6
        git submodule update --init
        pip install -r requirements.txt
        pip install -e .

    - name: Test chakra_trace_link Without Arguments
      run: |
        chakra_trace_link || [ $? -eq 2 ]

    - name: Test chakra_converter Without Arguments
      run: |
        chakra_converter || [ $? -eq 2 ]

    - name: Test chakra_visualizer Without Arguments
      run: |
        chakra_visualizer || [ $? -eq 2 ]

    - name: Test chakra_jsonizer Without Arguments
      run: |
        chakra_jsonizer || [ $? -eq 2 ]

    - name: Test chakra_timeline_visualizer Without Arguments
      run: |
        chakra_timeline_visualizer || [ $? -eq 2 ]
